ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - init: . .venv/bin/activate && pip install Flask

vscode:
  extensions:
    - svelte.svelte-vscode
    - eamodio.gitlens
    - ms-python.python
    - bradlc.vscode-tailwindcss
    - WakaTime.vscode-wakatime
    - formulahendry.auto-rename-tag
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode