ports:
  - port: 5173
    onOpen: open-preview

tasks:
  - init: npm install -g bun && bun install --cwd /workspace/folding/

vscode:
  extensions:
    - svelte.svelte-vscode
    - eamodio.gitlens
    - ms-python.python
    - bradlc.vscode-tailwindcss
    - WakaTime.vscode-wakatime
    - formulahendry.auto-rename-tag
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode