ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - init: "cd /workspace/folding && python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - bradlc.vscode-tailwindcss
    - WakaTime.vscode-wakatime
    - formulahendry.auto-rename-tag
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode